kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    project: expense
    environment: dev
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: web
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: web
    spec:
      containers:
      - name: backend
        image: swaroop02/backend:j1.0  

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    project: expense
    environment: dev
    tier: web
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # targetport