kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    project: expense
    environment: dev
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: db
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: swaroop02/mysql:1.0  

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    project: expense
    environment: dev
    tier: db
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # targetport